Task 2
kosmisa/test-test pull request #1
Opened 2023-04-21 20:14 UTC by kosmisa

Je l' dobro ovo odradjeno? 

Sto se tice pull req preko sajta sam odradio, pushovao sam promene ali pull req mi je iskljucivo preko sajta. Sad se rade t3 i t4

2023-04-21 20:15 UTC, kosmisa commented
E i sta su u gornjem desnom uglu zeleni i crveni brojevi???

2023-04-22 10:17 UTC, ZexTar commented
> Je l' dobro ovo odradjeno?
> 
> Sto se tice pull req preko sajta sam odradio, pushovao sam promene ali pull req mi je iskljucivo preko sajta. Sad se rade t3 i t4

super je ovo, samo pogledaj ima nekih par sitnica


> E i sta su u gornjem desnom uglu zeleni i crveni brojevi???
zeleno je broj dodatih a crveno broj izbrisanih linija u odnosu na target branch (u tvom slucaju master)

2023-04-22 10:18 UTC, ZexTar requested changes
popravi samo par sitnica pa pushuj i onda mergamo

2023-04-22 10:18 UTC, ZexTar commented on src/App.js
> +  const sortedNumbersArr = sorting.map((number) => {
ovo je dobro samo nazivi promenljivih treba da budu malo deskriptivniji zbog citljivosti, na primer:

```
const combinedData = [...data, ...asyncData];
const uniqueNumbers = [...new Set(combinedData)];

const sortedNumbers = uniqueNumbers.sort((a, b) => a - b);

const sortedNumberElements = sortedNumbers...
```

2023-04-22 10:18 UTC, ZexTar commented on src/App.js
>      <>
mislim da su ti fragmenti <> </> visak

2023-04-22 10:18 UTC, ZexTar commented on src/Apptest.js
>            <Fragment>
uvek koristi shorthand za fragmente, znaci umesto:

```
<Fragment>
...
</Fragment>
```

koristi:

```
<>
...
</>
```

https://react.dev/reference/react/Fragment

pazi na react dokumentaciju, nova dokumentacija je ovde - https://react.dev/reference/react, stara nije vise validna.

2023-04-22 11:47 UTC, kosmisa commented on src/Apptest.js
>            <Fragment>
komentarisao si mi Apptest.js koji se ne koristi on je tu samo za mene. Da ja gledam sta sam prvobitno radio. Mislim ok je da komentarises ali cisto da napomenem.

2023-04-22 11:50 UTC, kosmisa commented
Prepravke su odradjene. Jos nesto?

2023-04-22 14:43 UTC, ZexTar commented on src/App.js
>      <>
visak su ti fragmenti u mapu, trebas ovako pisati:

```
return (
    <>
      {sortedNumberElements.map((number) => (
        <p>{number}</p>
      ))}
    </>
  );
```

2023-04-22 17:54 UTC, kosmisa commented on src/App.js
>      <>
Obrisano

2023-04-22 18:11 UTC, ZexTar approved these changes
mozes merge

2023-04-22 19:53 UTC, merged